"""
Generate the complete static Bundesland → Bezirke mapping using pgeocode.
Scans all Austrian postal codes (1000–9999), groups cleaned county_name by state.
Output: TypeScript const for the frontend.
"""
import pgeocode, re
from collections import defaultdict

nomi = pgeocode.Nominatim("AT")

# Wien Bezirke (formula-based, not from GeoNames)
WIEN_BEZIRKE = {
    1: "Innere Stadt", 2: "Leopoldstadt", 3: "Landstraße", 4: "Wieden",
    5: "Margareten", 6: "Mariahilf", 7: "Neubau", 8: "Josefstadt",
    9: "Alsergrund", 10: "Favoriten", 11: "Simmering", 12: "Meidling",
    13: "Hietzing", 14: "Penzing", 15: "Rudolfsheim-Fünfhaus",
    16: "Ottakring", 17: "Hernals", 18: "Währing", 19: "Döbling",
    20: "Brigittenau", 21: "Floridsdorf", 22: "Donaustadt", 23: "Liesing",
}

def clean_county(s: str) -> str | None:
    s = str(s)
    if s == "nan" or not s:
        return None
    s = re.sub(r"^Politischer Bezirk ", "", s)
    s = re.sub(r" Stadt$", "", s)
    # Fix "Wien (Stadt)" → skip (Wien is handled separately)
    if "Wien" in s and "Bezirk" in s:
        return None
    return s.strip() or None

# Normalize Bundesland names to our app's naming
BL_MAP = {
    "Wien": "Wien",
    "Niederösterreich": "Niederösterreich",
    "Oberösterreich": "Oberösterreich",
    "Steiermark": "Steiermark",
    "Tirol": "Tirol",
    "Kärnten": "Kärnten",
    "Salzburg": "Salzburg",
    "Vorarlberg": "Vorarlberg",
    "Burgenland": "Burgenland",
}

by_bundesland: dict[str, set[str]] = defaultdict(set)

# Wien: all 23 Bezirke
for num, name in WIEN_BEZIRKE.items():
    by_bundesland["Wien"].add(f"{num}. Bezirk – {name}")

# Scan all other PLZ ranges
print("Scanning PLZ 2000–9999...")
plz_list = [str(p).zfill(4) for p in range(2000, 10000)]
results = nomi.query_postal_code(plz_list)

for _, row in results.iterrows():
    state = str(row.get("state_name", ""))
    county = clean_county(row.get("county_name", ""))
    if not state or state == "nan" or not county:
        continue
    bl = BL_MAP.get(state)
    if bl and bl != "Wien":
        by_bundesland[bl].add(county)

# Sort
output: dict[str, list[str]] = {}
# Wien: sort numerically
output["Wien"] = sorted(by_bundesland["Wien"], key=lambda x: int(x.split(".")[0]))
# Others: alphabetically, but put "Graz" / "Linz" etc. (Statutarstädte) first
for bl in ["Niederösterreich", "Oberösterreich", "Steiermark", "Tirol",
           "Kärnten", "Salzburg", "Vorarlberg", "Burgenland"]:
    output[bl] = sorted(by_bundesland[bl])

print("\n// Auto-generated by gen_bezirk_list.py")
print("export const BEZIRKE_BY_BUNDESLAND: Record<string, string[]> = {")
for bl, bezirke in output.items():
    print(f'  "{bl}": [')
    for b in bezirke:
        print(f'    "{b}",')
    print("  ],")
print("}")

print(f"\n// Totals:")
for bl, bezirke in output.items():
    print(f"//   {bl}: {len(bezirke)}")
