from pymongo import MongoClient
import os
from dotenv import load_dotenv
load_dotenv('Backend/.env')
uri = os.getenv('MONGODB_URI')
client = MongoClient(uri)
db = client['padel_checker']
venues = db['venues']

docs = [
    # smash Trumau - 1 outdoor court
    {
        'id': 'smash-trumau',
        'active': True,
        'address': 'Hauptstraße 1a, 2490 Trumau',
        'booking_url': 'https://www.eversports.at/sb/smash-trumau',
        'court_type': 'outdoor',
        'courts': [{'id': '112752', 'type': 'outdoor_normal'}],
        'etennis_id': None,
        'eversports_court_ids': [112752],
        'eversports_facility_id': 83703,
        'eversports_slug': 'smash-trumau',
        'issues': None,
        'lat': 47.9954,
        'lon': 16.3433,
        'maps_id': 'https://www.google.com/maps?q=47.9954,16.3433',
        'name': 'Smash Trumau',
        'notes': None,
        'operator': 'Smash Group',
        'platform': 'Eversports',
        'platform_id': 'smash-trumau',
        'priority': 6,
        'public_url': 'https://www.smash-group.com',
        'region_key': 'niederoesterreich',
        'region_label': 'Niederösterreich',
        'slot_fallback_minutes': [],
        'bezirk': None,
    },
    # smash Bruck an der Leitha - 2 outdoor courts
    {
        'id': 'smash-bruck-an-der-leitha',
        'active': True,
        'address': 'Fischamender Straße 2, 2460 Bruck an der Leitha',
        'booking_url': 'https://www.eversports.at/sb/smash-bruck-an-der-leitha',
        'court_type': 'outdoor',
        'courts': [{'id': '113152', 'type': 'outdoor_normal'}, {'id': '113153', 'type': 'outdoor_normal'}],
        'etennis_id': None,
        'eversports_court_ids': [113152, 113153],
        'eversports_facility_id': 83701,
        'eversports_slug': 'smash-bruck-an-der-leitha',
        'issues': None,
        'lat': 48.0171,
        'lon': 16.7759,
        'maps_id': 'https://www.google.com/maps?q=48.0171,16.7759',
        'name': 'Smash Bruck an der Leitha',
        'notes': None,
        'operator': 'Smash Group',
        'platform': 'Eversports',
        'platform_id': 'smash-bruck-an-der-leitha',
        'priority': 6,
        'public_url': 'https://www.smash-group.com',
        'region_key': 'niederoesterreich',
        'region_label': 'Niederösterreich',
        'slot_fallback_minutes': [],
        'bezirk': None,
    },
    # Coming-soon venues (active: false)
    {
        'id': 'smash-schwadorf',
        'active': False,
        'address': 'Schwadorf, Niederösterreich',
        'booking_url': 'https://www.eversports.at/sb/smash-schwadorf',
        'court_type': 'outdoor',
        'courts': [],
        'etennis_id': None,
        'eversports_court_ids': [],
        'eversports_facility_id': None,
        'eversports_slug': 'smash-schwadorf',
        'issues': None,
        'lat': 48.0622,
        'lon': 16.5647,
        'maps_id': None,
        'name': 'Smash Schwadorf',
        'notes': 'Coming soon June 2026',
        'operator': 'Smash Group',
        'platform': 'Eversports',
        'platform_id': 'smash-schwadorf',
        'priority': 3,
        'public_url': 'https://www.smash-group.com',
        'region_key': 'niederoesterreich',
        'region_label': 'Niederösterreich',
        'slot_fallback_minutes': [],
        'bezirk': None,
    },
    {
        'id': 'smash-mitterndorf',
        'active': False,
        'address': 'Mitterndorf an der Fischa, Niederösterreich',
        'booking_url': 'https://www.eversports.at/sb/smash-mitterndorf',
        'court_type': 'outdoor',
        'courts': [],
        'etennis_id': None,
        'eversports_court_ids': [],
        'eversports_facility_id': None,
        'eversports_slug': 'smash-mitterndorf',
        'issues': None,
        'lat': 48.0342,
        'lon': 16.5281,
        'maps_id': None,
        'name': 'Smash Mitterndorf',
        'notes': 'Coming soon October 2026',
        'operator': 'Smash Group',
        'platform': 'Eversports',
        'platform_id': 'smash-mitterndorf',
        'priority': 3,
        'public_url': 'https://www.smash-group.com',
        'region_key': 'niederoesterreich',
        'region_label': 'Niederösterreich',
        'slot_fallback_minutes': [],
        'bezirk': None,
    },
    {
        'id': 'smash-stockerau',
        'active': False,
        'address': 'Stockerau, Niederösterreich',
        'booking_url': 'https://www.eversports.at/sb/smash-stockerau',
        'court_type': 'outdoor',
        'courts': [],
        'etennis_id': None,
        'eversports_court_ids': [],
        'eversports_facility_id': None,
        'eversports_slug': 'smash-stockerau',
        'issues': None,
        'lat': 48.3854,
        'lon': 16.2097,
        'maps_id': None,
        'name': 'Smash Stockerau',
        'notes': 'Coming soon October 2026',
        'operator': 'Smash Group',
        'platform': 'Eversports',
        'platform_id': 'smash-stockerau',
        'priority': 3,
        'public_url': 'https://www.smash-group.com',
        'region_key': 'niederoesterreich',
        'region_label': 'Niederösterreich',
        'slot_fallback_minutes': [],
        'bezirk': None,
    },
    {
        'id': 'smash-wien-indoor',
        'active': False,
        'address': 'Wien',
        'booking_url': 'https://www.eversports.at/sb/smash-wien-indoor',
        'court_type': 'indoor',
        'courts': [],
        'etennis_id': None,
        'eversports_court_ids': [],
        'eversports_facility_id': None,
        'eversports_slug': 'smash-wien-indoor',
        'issues': None,
        'lat': 48.2082,
        'lon': 16.3738,
        'maps_id': None,
        'name': 'Smash Wien Indoor',
        'notes': 'Coming soon, date TBD',
        'operator': 'Smash Group',
        'platform': 'Eversports',
        'platform_id': 'smash-wien-indoor',
        'priority': 3,
        'public_url': 'https://www.smash-group.com',
        'region_key': 'wien',
        'region_label': 'Wien',
        'slot_fallback_minutes': [],
        'bezirk': None,
    },
]

result = venues.insert_many(docs)
print('Inserted', len(result.inserted_ids), 'venues')
for doc, iid in zip(docs, result.inserted_ids):
    print(f"  {doc['id']} (active={doc['active']}) -> {iid}")
